language: java
sudo: false
dist: trusty
matrix:
  include:
    - jdk: "oraclejdk8"
before_install:
  - pip install --user codecov
script:
  - ./gradlew check junit5CodeCoverageReport
after_success:
  - codecov
