language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - pip install --user codecov
script:
  - ./gradlew check junit5CodeCoverageReport
after_success:
  - codecov
