blank_issues_enabled: false
contact_links:
  - name: Question (GitHub Discussions)
    url: https://github.com/junit-team/junit5/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Question (Stack Overflow)
    url: https://stackoverflow.com/questions/tagged/junit5
    about: Alternatively, ask questions here.
